import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://bookslot-staging.centerforvein.com/basic-info")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("link", name="-697-5849  |").click()
    page.get_by_role("button", name="English").click()
    page.get_by_role("button", name="English").click()
    page.get_by_role("heading", name="We need to collect some").click()
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_text("Please fill the required").click()
    page.locator(".field.py-1.col-12.ng-star-inserted").click()
    page.get_by_text("Please fill the required fields (marked with *).- First Name- Last Name- E-mail").click()
    page.get_by_text("- First Name").click()
    page.get_by_text("- Last Name").click()
    page.get_by_text("- E-mail").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Zip Code").click()
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="First Name *").fill("Test")
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_text("Please fill the required fields (marked with *).- Last Name- E-mail- Cell Phone").click()
    page.get_by_text("- Last Name").click()
    page.get_by_text("- E-mail").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Zip Code").click()
    page.get_by_role("textbox", name="Last Name *").click()
    page.get_by_role("textbox", name="Last Name *").fill("Test")
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_text("Please fill the required").click()
    page.get_by_text("- E-mail").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Zip Code").click()
    page.get_by_role("textbox", name="E-mail *").click()
    page.get_by_role("textbox", name="E-mail *").fill("test@test")
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_role("textbox", name="E-mail *").click()
    page.get_by_role("textbox", name="E-mail *").fill("test@test.com")
    page.locator("div").filter(has_text=re.compile(r"^Please fill the required fields \(marked with \*\)\.- Cell Phone Number- Zip Code$")).first.click()
    page.get_by_text("Please fill the required").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Cell Phone Number").click()
    page.get_by_text("- Zip Code").click()
    page.locator("#CellPhone").get_by_role("textbox").click()
    page.get_by_role("button", name="Send Me The Code").click()
    page.locator("#ZipCode").click()
    page.locator("#ZipCode").fill("20678")
    page.get_by_role("button", name="Send Me The Code").click()
    page.get_by_text("Please enter the 6-digit verification code.Code Verify Code").click()
    page.get_by_role("button", name="Verify Code").click()
