import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://bookslots.centerforvein.com/basic-info")
    page.get_by_role("button", name="English").click()
    page.get_by_role("button", name="Español").click()
    page.get_by_role("button", name="English").click()
    page.get_by_role("heading", name="We need to collect some").click()
    page.get_by_role("heading", name="Fields marked with * are").click()
    page.get_by_text("First Name *").click()
    page.locator("label").filter(has_text="First Name *").locator("span").click()
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="First Name *").fill("ProdTester007")
    page.get_by_text("Last Name *").click()
    page.locator("label").filter(has_text="Last Name *").locator("span").click()
    page.get_by_role("textbox", name="Last Name *").click()
    page.get_by_role("textbox", name="Last Name *").fill("Test")
    page.get_by_text("E-mail *").click()
    page.locator("label").filter(has_text="E-mail *").locator("span").click()
    page.get_by_role("textbox", name="E-mail *").click()
    page.get_by_role("textbox", name="E-mail *").fill("prdotester0077@mailinator.com")
    page.get_by_text("Cell Phone Number *").click()
    page.get_by_text("*").nth(4).click()
    page.locator("#CellPhone").get_by_role("textbox").click()
    page.get_by_text("Zip Code * (Please enter the").click()
    page.get_by_text("(Please enter the zip code").click()
    page.locator("#ZipCode").click()
    page.locator("#ZipCode").fill("20678")
    page.get_by_role("radio", name="Text").check()
    page.get_by_role("radio", name="E-mail").check()
    page.get_by_role("radio", name="Call").check()
    page.get_by_role("radio", name="Text").check()
    page.get_by_role("button", name="Send Me The Code").click()
    page.locator("#loader").click()
    page.get_by_text("Please enter the 6-digit verification code.Code Verify Code").click()
    page.get_by_role("button", name="Verify Code").click()
    page.get_by_role("button", name="Request Call back").click()
    page.get_by_text("Request has been submitted").click()
    page.get_by_role("heading", name="New Patient Appointment").click()
    page.get_by_text("90-minute appointment with").click()
    page.get_by_role("heading", name="Complimentary Consultation").click()
    page.get_by_text("15-minute appointmentwith a").click()
    page.locator("div").filter(has_text="New Patient Appointment90-").nth(5).click()
    page.get_by_role("button", name="Book Now").first.click()
    page.get_by_role("combobox").first.click()
    page.get_by_role("button", name="Next Month").click()
    page.get_by_role("button", name="Next Month").click()
    page.get_by_role("button", name="Next Month").click()
    page.get_by_text("26", exact=True).click()
    page.get_by_role("combobox").nth(1).click()
    page.get_by_role("button", name="Next Month").click()
    page.get_by_role("button", name="Next Month").click()
    page.get_by_role("button", name="Next Month").click()
    page.get_by_role("gridcell", name="26").click()
    page.get_by_role("button", name="Previous Month").click()
    page.get_by_role("button", name="Previous Month").click()
    page.get_by_role("button", name="Previous Month").click()
    page.locator("span").filter(has_text=re.compile(r"^28$")).click()
    page.get_by_role("combobox").first.click()
    page.get_by_role("button", name="Previous Month").click()
    page.get_by_role("button", name="Previous Month").click()
    page.get_by_text("22").click()
    page.get_by_role("textbox").first.click()
    page.get_by_role("textbox").first.fill("5")
    page.locator("#miles-div").get_by_role("button").click()
    page.get_by_role("textbox").nth(1).click()
    page.get_by_role("textbox").nth(1).press("ArrowRight")
    page.get_by_role("textbox").nth(1).press("ArrowRight")
    page.get_by_role("textbox").nth(1).press("ArrowRight")
    page.get_by_role("textbox").nth(1).press("ArrowRight")
    page.get_by_role("textbox").nth(1).press("ArrowRight")
    page.get_by_role("textbox").nth(1).fill("20678")
    page.locator("#miles-div").get_by_role("button").click()
    page.get_by_role("textbox").first.click()
    page.get_by_role("textbox").first.fill("5")
    page.locator("#miles-div").get_by_role("button").click()
    page.get_by_text("We couldn't find appointments").click()
    page.get_by_role("button", name="CVR - MD - Prince Frederick").click()
    page.get_by_role("button", name="CVR - MD - Prince Frederick").click()
    page.locator("div").filter(has_text=re.compile(r"^Tue, Feb 24 - Tue, Mar 17$")).nth(1).click()
    page.get_by_label("CVR - MD - Prince").get_by_text("Tue, Feb 24 - Tue, Mar").click()
    page.locator("i").nth(1).click()
    page.get_by_label("CVR - MD - Prince").get_by_text("Thu09Apr").click()
    page.get_by_role("button", name="06:00 AM").click()
    page.get_by_role("button", name="CVR - MD - Prince Frederick").click()
    page.locator("i").nth(1).click()
    page.get_by_role("button", name=":00 AM").click()
    page.locator(".card").first.click()
    page.get_by_role("heading", name="Request an Appointment").click()
    page.get_by_text("This spot is reserved for the").click()
    page.get_by_role("heading", name="Appointment Details").click()
    page.get_by_text("Appointment Details Thursday").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="Middle Name").click()
    page.get_by_role("textbox", name="Middle Name").fill("Test")
    page.get_by_text("Last Name *").click()
    page.get_by_role("textbox", name="Last Name *").click()
    page.get_by_text("Sex *").click()
    page.get_by_text("*").nth(3).click()
    page.get_by_role("combobox", name="Select Gender").click()
    page.get_by_role("option", name="MALE", exact=True).click()
    page.get_by_text("Cell Phone Number *").click()
    page.get_by_text("*").nth(4).click()
    page.get_by_text("Secondary Phone Number").click()
    page.locator("#CellPhoneSec").get_by_role("textbox").click()
    page.get_by_text("E-mail *").click()
    page.get_by_text("*").nth(5).click()
    page.get_by_role("textbox", name="E-mail *").click()
    page.get_by_text("Date of Birth *").click()
    page.get_by_text("*", exact=True).nth(5).click()
    page.get_by_role("combobox", name="mm/dd/yyyy").click()
    page.get_by_role("combobox", name="mm/dd/yyyy").fill("01/01/2000")
    page.get_by_role("textbox", name="Address").click()
    page.get_by_role("textbox", name="Address").fill("20678")
    page.get_by_text("338Highmore, SD, USA").click()
    page.get_by_text("Add your address").click()
    page.get_by_text("Country").click()
    page.get_by_role("textbox", name="Country").click()
    page.get_by_text("Zip Code").click()
    page.get_by_role("textbox", name="Zip Code").click()
    page.get_by_text("City").click()
    page.get_by_role("textbox", name="City").click()
    page.get_by_text("State").click()
    page.get_by_role("textbox", name="State").click()
    page.get_by_role("button", name="Next").click()
    page.locator("div").filter(has_text=re.compile(r"^How did you hear about us\?$")).nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^Referred by physician$")).click()
    page.get_by_role("button", name="Internet search").click()
    page.locator("div").filter(has_text=re.compile(r"^Facebook$")).click()
    page.get_by_role("button", name="Family/friend").click()
    page.get_by_role("button", name="TV/Print/Radio").click()
    page.get_by_role("button", name="Other").click()
    page.locator("#otherReferral").click()
    page.locator("#otherReferral").fill("Test")
    page.get_by_role("button", name="Next").click()
    page.get_by_role("textbox", name="Member Name *").click()
    page.get_by_role("textbox", name="Member Name *").fill("Tester Test")
    page.get_by_role("textbox", name="ID Number *").click()
    page.get_by_role("textbox", name="ID Number *").fill("123456")
    page.get_by_text("Member Name *").click()
    page.locator("label").filter(has_text="Member Name *").locator("span").click()
    page.get_by_text("ID Number *").click()
    page.get_by_text("*").nth(2).click()
    page.get_by_text("Group number *").click()
    page.get_by_text("*").nth(3).click()
    page.get_by_text("Insurance Company Name *").click()
    page.get_by_text("*").nth(4).click()
    page.get_by_text("Insurance Company Name *").click()
    page.get_by_role("textbox", name="Group number *").click()
    page.get_by_role("textbox", name="Group number *").fill("123456")
    page.get_by_text("Insurance Company Name *").click()
    page.get_by_text("*").nth(4).click()
    page.get_by_role("textbox", name="Insurance Company Name *").click()
    page.get_by_role("textbox", name="Insurance Company Name *").fill("Cigna")
    page.get_by_role("button", name="Send to clinic").click()
    page.get_by_text("Success!").click()
    page.locator("div").filter(has_text=re.compile(r"^Your appointment has been booked\.$")).click()
    page.get_by_text("We have received your").click()
    page.get_by_text("If you have any questions,").click()
    page.get_by_role("link", name="240-697-0612", exact=True).click()
    page.get_by_role("button", name="Accept All").click()
    page.get_by_role("banner").get_by_role("link", name="Home").click()
